### ISSUE TITLE
vignette is failing due to specific path to data directories

### ISSUE THREAD

**Issue by brunj7** [kylemonper/CamelsQuery#4]
not sure how to best handle this.

**Comment by kylemonper** [comment]
some thoughts on this:
1. we can skip the vignette and just create a walkthrough pdf/rmd
2. (not sure how feasible this is) we can create some dummy data/ load specific text files into the package data to be used as a reference. though this might make the vignette a little confusing

**Comment by kylemonper** [comment]
3. also, if we make the function for downloading the ncar data we could add that into the vignette so we could create the directories for the user, only downside would be it'll take a long time to download and unzip

**Comment by kylemonper** [comment]
set eval = F, otherwise is a functional workflow
